import mongoose, { Schema } from 'mongoose'

const listingSchema = new Schema(
  {
    listingId: { type: String, required: true, unique: true },
    agencyId: { type: String, required: true, index: true },
    agencyName: { type: String, default: '' },
    title: { type: String, required: true },
    mediaCategory: {
      type: String,
      enum: ['OOH', 'TV', 'Radio', 'Press', 'ContentCreators'],
      default: 'OOH',
    },
    mediaType: { type: String, required: true },
    subcategory: { type: String, default: '' },
    subcategoryId: { type: String, default: null },
    emirate: { type: String, default: 'Dubai' },
    city: { type: String, default: 'Dubai' },
    area: { type: String, default: '' },
    landmark: { type: String, default: '' },
    sizeWidth: { type: String, default: '' },
    sizeHeight: { type: String, default: '' },
    sizeUnit: { type: String, default: 'm' },
    pricingType: {
      type: String,
      enum: ['fixed', 'range', 'starting_price', 'on_request'],
      default: 'range',
    },
    priceMin: { type: Number, default: 0 },
    priceMax: { type: Number, default: 0 },
    billingDuration: {
      type: String,
      enum: ['per_day', 'per_week', 'per_month', 'per_campaign', 'per_spot', 'custom'],
      default: 'per_month',
    },
    customDurationLabel: { type: String, default: '' },
    oohType: { type: String, default: '' },
    mediaTypeDetail: { type: String, default: '' },
    objectives: { type: [String], default: [] },
    assetOwnership: { type: String, enum: ['owned', 'leased', null], default: null },
    aboutPlacement: { type: String, default: '' },
    submissionType: { type: String, enum: ['create', 'edit'], default: 'create' },
    availability: { type: String, default: 'immediate' },
    descriptionShort: { type: String, default: '' },
    descriptionLong: { type: String, default: '' },
    imageUrl: { type: String, default: '' },
    galleryImages: { type: [String], default: [] },
    deliverables: { type: [String], default: [] },
    isDirectMedia: { type: Boolean, default: false },
    lat: { type: Number, default: 25.2048 },
    lng: { type: Number, default: 55.2708 },
    status: {
      type: String,
      enum: ['draft', 'pending_approval', 'pending_edit_approval', 'approved', 'rejected', 'archived'],
      default: 'draft',
    },
    rejectionReason: { type: String, default: null },
    submittedAt: { type: String, default: null },
    reviewedAt: { type: String, default: null },
    delistedAt: { type: String, default: null },
    documents: { type: [Schema.Types.Mixed], default: [] },
    rating: { type: Number, default: 4.5 },
    format: { type: String, default: 'billboard' },
  },
  { timestamps: true },
)

export const Listing = mongoose.model('Listing', listingSchema)
